### ISSUE TITLE
Loadbalancer backend support attach service endpoint address directly

### ISSUE THREAD

**Issue by jolestar** [yunify/qingcloud-cloud-controller-manager#4]
Kubernetes LoadBalancer backend is service NodePort currently, there are some shortcomings:

1. Performance waste
2. Service get client real source ip is complicated 

So, attach service endpoint address to Loadbalancer backend directly when use hostnic network. 

The following improvements are required to achieve this goal：

1. Watch service endpoint change by kubernetes api.
2. Update loadbalancer backend when service endpoint change.

Should provide a config option to control this feature.

**Comment by magicsong** [comment]
As cloud-provider are not advised to watch any k8s resource(**we have no place to write long-run go-routine but in `main.go`**, and main.go using `init` to register cloud-provider because we use interface to fulfill functions), the solution is not possible. Unless write another new controller.
 
there is a workround for 1: <https://github.com/kubesphere/porter/issues/50#issuecomment-481938591>
task 2 has been done in iaas
